import = ["/home/dpar/.config/alacritty/colors/doom_one.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[shell]
args = ["--login"]
program = "/usr/bin/zsh"

[window]
dynamic_title = false
opacity = 1.0
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 80
lines = 20

[window.padding]
x = 6
y = 6

[scrolling]
history = 10000
multiplier = 3

[font]
size = 12

[font.bold]
family = "Fira Code SS"
style = "Bold"

[font.bold_italic]
family = "Fira Code SS"
style = "Bold Italic"

[font.italic]
family = "Fira Code SS"
style = "Italic"

[font.normal]
family = "Fira Code SS"
style = "Regular"

[font.offset]
x = 0
y = 0

[cursor]
blink_interval = 900
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Block"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

