-- vim.api.nvim_create_autocmd("BufEnter", {
--   group = vim.api.nvim_create_augroup("custom-no-config", {}),
--   callback = function(e)
--     local s, _ = e.file:find("^" .. vim.fn.stdpath("config"))
--     if s ~= nil then
--       vim.notify("NO MESSING WITH NVIM CONFIG", vim.log.levels.ERROR)
--       vim.api.nvim_buf_delete(e.buf, {})
--       print("NO MESSING WITH NVIM CONFIG")
--     end
--   end,
-- })
