require("cold").load()
vim.api.nvim_set_hl(0, "DiagnosticHint", { fg = "#576f82" })
vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = "#ab8550" })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = "#ab8550" })
vim.api.nvim_set_hl(0, "DiagnosticError", { fg = "#984936" })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineHint", { undercurl = false, underline = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineInfo", { undercurl = false, underline = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineWarn", { undercurl = false, underline = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineError", { undercurl = false, underline = true })
vim.api.nvim_set_hl(0, "DiagnosticUnnecessary", { fg = "#585858", undercurl = false, underline = true })
