#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# env set up
export TMPDIR=/tmp # for discord rtp and prob other stuff
#export EDITOR=nvim
export XDG_RUNTIME_DIR=/tmp/runtime-dpar
# for vscode setting sync
#gnome-keyring-daemon & # Doesnt acutally work

# Keyboard
setxkbmap us &
xset r rate 400 45 & # set key repeat rate
xset b 0 & # kill bell volume

picom &
clipit -d &

xbacklight 20 &
exec $@

