#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# env set up
export TMPDIR=/tmp # for discord rtp and prob other stuff
export XDG_RUNTIME_DIR=/tmp/runtime-dpar
export XDG_CONFIG_DIR=$HOME/.config
# for vscode setting sync
#gnome-keyring-daemon & # Doesnt acutally work

# Keyboard
setxkbmap us &
xset r rate 400 45 & # set key repeat rate
xset b 0 & # kill bell volume
# set mouse accel to acceptable levels libinput / evdev
#xinput --set-prop 13 'libinput Accel Speed' -0.40
xinput --set-prop 13 'Device Accel Profile' 0 1
xinput --set-prop 13 'Device Accel Constant Deceleration' 1.50
picom &
clipit -d &

#exec $@
exec dbus-launch --sh-syntax --exit-with-session "$@"

