#!/usr/bin/env bash

pgrep -x sxhkd > /dev/null || SXHKD_SHELL=/usr/bin/sh sxhkd &

INTERNAL_MONITOR="eDP"
EXTERNAL_MONITOR="HDMI-A-0"

# on first load setup default workspaces
if [[ "$1" = 0 ]]; then
  if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
    bspc monitor "$EXTERNAL_MONITOR" -d 1 2 3 4 5
    bspc monitor "$INTERNAL_MONITOR" -d 6 7 8 9 10
    bspc wm -O "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"
  else
    bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5 6 7 8 9 10
  fi
fi

eww daemon &
eww open bar &
#echo $PATH >> ~/path
#echo $(which eww) >> ~/path
/home/dpar/.local/bin/monsoon &

~/.local/bin/setup_monitors_bspwm.sh

bspc config border_width         1
bspc config window_gap			 0

bspc config focus_follows_pointer	true

bspc config single_monocle		 true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a zoom desktop='^2' state=floating border=off
bspc rule -a feh state=floating
bspc rule -a Steam state=floating
