#!/usr/bin/env bash

pgrep -x sxhkd > /dev/null || SXHKD_SHELL=/usr/bin/sh sxhkd &

PRIMARY_MONITOR="DP-0"
SECONDARY_MONITOR="HDMI-0"

# on first load setup default workspaces
if [[ "$1" = 0 ]]; then
  if [[ $(xrandr -q | grep "${SECONDARY_MONITOR} connected") ]]; then
    bspc monitor "$PRIMARY_MONITOR" -d 1 2 3 4 5
    bspc monitor "$SECONDARY_MONITOR" -d 6 7 8 9 10
  else
    bspc monitor "$PRIMARY_MONITOR" -d 1 2 3 4 5 6 7 8 9 10
  fi

  # set up proper rot + pos
  xrandr --output DP-0 --mode 1920x1080 -r 144 \
        --output HDMI-0 --mode 1920x1080 -r 60 --rotation left --left-of DP-0

fi

#eww daemon &
#eww open bar &
#polybar & disown
$HOME/.config/polybar/launch.sh &

bspc wm --reorder-monitors "$PRIMARY_MONITOR" "$SECONDARY_MONITOR"
~/.fehbg &
xsetroot -cursor_name left_ptr &

# detect monitor changes, shouldnt need on desktop
#~/.local/bin/setup_monitors_bspwm.sh

bspc config border_width         1
bspc config focused_border_color  "#606060"
bspc config window_gap			 0

bspc config focus_follows_pointer	true

bspc config single_monocle		 true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a zoom state=floating
bspc rule -a zathura desktop='^3'
bspc rule -a feh state=floating
bspc rule -a Steam state=floating

