format = """
$directory\
$git_branch$git_commit$git_state$git_status\
$bun\
$deno\
$golang\
$nodejs\
$python\
$rust\
$zig\
$cmd_duration\
$line_break$character"""

[character]
success_symbol = "[Œª](bold green)"
error_symbol = "[Œª](bold red)"
[git_branch]
# format = "[\\[](bold bright-black)[$symbol$branch(:$remote_branch)]($style)[\\]](bold bright-black)"
# format = "[\\[](bold bright-black)[$symbol$branch(:$remote_branch)]($style)[\\]](bold bright-black)"
ignore_branches = ["main", "master"]
[git_commit]
format = "[\\([$hash](green bold)[$tag](bright-green bold)\\)](bold green) "
tag_symbol = " "
tag_disabled = false
[git_state]
format = "[\\($state( $progress_current/$progress_total)\\)]($style) "
[git_status]
# format = "([\\[](bold bright-black)[$all_status$ahead_behind]($style)[\\]](bold bright-black))"
[bun]
symbol = "üçû "
style = "bold bright-red"
format = "[\\[](bold bright-black)[$symbol($version)]($style)[\\]](bold bright-black) "
[deno]
format = "[\\[](bold bright-black)[$symbol($version)]($style)[\\]](bold bright-black) "
[golang]
format = "[\\[](bold bright-black)[$symbol($version)]($style)[\\]](bold bright-black) "
[nodejs]
format = "[\\[](bold bright-black)[$symbol($version)]($style)[\\]](bold bright-black) "
[python]
format = "[\\[](bold bright-black)[${symbol}$version(\\($virtualenv\\))]($style)[\\]](bold bright-black) "
[rust]
format = "[\\[](bold bright-black)[$symbol($version)]($style)[\\]](bold bright-black) "
style = "bold bright-red"
[zig]
format = "[\\[](bold bright-black)[$symbol($version)]($style)[\\]](bold bright-black) "
symbol = "‚ö°"
style = "#fab040"
[cmd_duration]
format = "[$duration]($style)"
min_time = 10_000

