#format = "$directory$git_branch$shlvl[>](bold black) "
scan_timeout = 10
command_timeout = 200

[directory]
truncate_to_repo = true

[cmd_duration]
disabled = true

#[git_branch]
#format = '[$symbol$branch]($style) '

#[shlvl]
#disabled = false
#threshold = 5
#format = '[$shlvl ]($style)'

