format = "$directory$git_branch$git_status$shlvl[>](bold black) "
add_newline = false
scan_timeout = 10

[directory]
truncate_to_repo = true

[git_branch]
format = '[$symbol$branch]($style) '


[shlvl]
disabled = false
threshold = 5
format = '[$shlvl ]($style)'

[status]
disabled = true
pipestatus = true
pipestatus_format = '[$pipestatus]($style)'
format = '[\[$status$signal_name\]]($style)'

