#!/usr/bin/zsh

export PATH=$HOME/.local/bin:$PATH

export SHELL=/usr/bin/zsh
export XDG_CONFIG_HOME="$HOME/.config"
#export ZDOTDIR="$HOME/.config/zsh"

if hash nvim 2>/dev/null; then
    export EDITOR=nvim
    export MANPAGER='nvim +Man!'
else
    export EDITOR=vim
fi
export BROWSER="firefox"

if hash zf 2>/dev/null; then
    export ZF_HIGHLIGHT="green"
    export FILTER_PROG=zf
else
    export FILTER_PROG=fzf
fi
export DEV_ROOT="$HOME/dev"

export FZF_DEFAULT_OPTS='--color fg:242,bg:-1,hl:65,fg+:15,bg+:-1,hl+:108 --color info:108,prompt:109,spinner:108,pointer:168,marker:168'

export NVM_DIR="$HOME/.config/nvm"
export XDEB_PKGROOT="$HOME/.config/xdeb"

export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

